openapi: 3.0.3
info:
  title: vault-secret-encryptor-api
  description: vault-secret-encryptor-api
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
    description: localhost
paths:
  '/encrypt':
    post:
      operationId: encryptSecret
      description: Encrypt secret file
      tags:
        - Encrypt
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - serviceName
                - fileName
              properties:
                serviceName:
                  type: string
                fileName:
                  type: string
                  format: binary
      responses:
        '200':
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error

  
